# Generated by Django 2.2.1 on 2019-05-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=50)),
                ('sinopsis', models.TextField()),
                ('disponible', models.BooleanField(default=False)),
            ],
        ),
    ]
